source 'https://rubygems.org'

gem 'rake'
gem 'rspec'
gem 'rspec-collection_matchers'
gem 'rest-client'
gem 'aws-sdk'
gem 'net-sftp'

gem 'rubocop'
gem 'pry'
gem 'pry-nav'
gem 'guard-rspec'
gem 'terminal-notifier-guard'
gem 'terminal-notifier'
