#!/bin/bash

cd $(dirname $0)/..

if [ -z "$BITS_SERVICE_MANIFEST" ]; then
  echo "Error: The variable BITS_SERVICE_MANIFEST is not set."
  exit 1
fi

./scripts/generate-bosh-lite-manifest ./spec/assets/body-size-stub.yml ./templates/local.yml
./scripts/manifest_parser.rb ./deployments/bits-service-release-bosh-lite.yml > manifest.yml
bosh deployment manifest.yml

echo Now you can deploy and run \'bundle exec rake spec\'.
