#!/bin/bash -e

cd $(dirname $0)/../

mkdir -p deployments

spruce merge ../bits-service-ci/manifests/cf-lite.yml ../bits-service-ci/manifests/tweaks.yml \
  ../bits-service-ci/manifests/enable-bits.yml \
  ../bits-service-ci/manifests/bits-network-bosh-lite.yml \
  ./templates/local.yml \
  > deployments/cf-with-bits-service-enabled.yml

bosh deployment deployments/cf-with-bits-service-enabled.yml
