#!/bin/bash -ex

cd $(dirname $0)/..

mkdir -p deployments
MANIFEST_FILE=deployments/bits-service-release.yml

export BLOBSTORE_TYPE="${1:?Missing parameter indicating blobstore type}"; shift
export BOSH_DIRECTOR_UUID=not-used-anymore-in-cli-v2


echo "Using blobstore-type=${BLOBSTORE_TYPE} for manifest generation."

spruce merge --go-patch \
    templates/standalone-basic-structure.yml \
    templates/standalone-blobstore-job.yml \
    templates/standalone-bits-service-job.yml \
    templates/standalone-properties-${BLOBSTORE_TYPE}.yml \
    templates/body-size-stub.yml \
    "$@" \
  > ${MANIFEST_FILE}

bosh2 int ${MANIFEST_FILE} --vars-store ../bits-service-private-config/environments/softlayer/deployment-vars-${DEPLOYMENT_NAME}.yml > ${MANIFEST_FILE}-with-vars
mv ${MANIFEST_FILE}-with-vars ${MANIFEST_FILE}

echo "Manifest written to ${MANIFEST_FILE}"
