#!/bin/bash -e

[ "$#" -eq 0 ] && echo "Requires at least 1 stub" && exit 1

cd $(dirname $0)/..

mkdir -p deployments
MANIFEST_FILE=deployments/bits-service-release.yml

spruce merge \
    templates/director_uuid.yml \
    templates/bits-service.yml \
    templates/bits-service-signing-properties.yml \
    "$@" \
  > ${MANIFEST_FILE}

# Apply ERB templates
TMP=${MANIFEST_FILE}.tmp
scripts/manifest_parser.rb "${MANIFEST_FILE}" > "${MANIFEST_FILE}.tmp"
mv ${TMP} ${MANIFEST_FILE}
