#!/bin/bash -e

cd $(dirname $0)/..

./scripts/generate-bosh-manifest ./templates/blobstore-job.yml \
                                 ./templates/bosh-lite.yml \
                                 ./templates/body-size-stub.yml \
                                 $@

export BOSH_USE_BUNDLER=true
bosh deployment deployments/bits-service-release.yml

echo Now you can deploy and run \'bundle exec rake spec\'.
