#!/bin/bash -e

BLOBSTORE_TYPE=${1}

if [ -z "$BLOBSTORE_TYPE" ]; then
  >&2 echo "Please provide a BLOBSTORE_TYPE {local,s3,webdav}"
  exit 1
fi

cd $(dirname $0)/../

mkdir -p deployments

cf_yml=../cf-release/bosh-lite/deployments/cf.yml

if [ ! -f "$cf_yml" ]; then
  echo "Could not find $cf_yml. Consider running ../cf-release/scripts/generate-bosh-lite-dev-manifest to create it."
  exit 1
fi

spruce merge "$cf_yml" \
  ../bits-service-ci/manifests/bits-service.yml \
  ./templates/cc-blobstore-properties.yml \
  ./templates/bits-service-signing-properties.yml \
  ../bits-service-ci/manifests/tweaks.yml \
  ../bits-service-ci/manifests/enable-bits.yml \
  ../bits-service-ci/manifests/bits-network-bosh-lite.yml \
  ./templates/${BLOBSTORE_TYPE}.yml \
  ./templates/body-size-stub.yml \
  > deployments/cf-with-bits-service-enabled.yml

bosh deployment deployments/cf-with-bits-service-enabled.yml
