#!/bin/bash

set -e -x

# ensure gosub is installed (this will recompile it only if necessary)
go get github.com/vito/gosub
go install github.com/vito/gosub

{
  gosub list \
    -app github.com/cloudfoundry-incubator/bits-service-migration-tests/... \
    -test github.com/cloudfoundry-incubator/bits-service-migration-tests/...
} > /tmp/packages

cat /tmp/packages | xargs gosub sync -i src/bits-service
