#!/bin/bash
#
# Pipe ngingx metrics into statsd
#
# If the request
#
#   PUT /droplets/7100a3b3-1eeb-49b1-ad52-747a1071a854 HTTP/1.1
#
# took 0.120s, we'd like to send a `timing` metric to statsd:
#
#   droplets-time:0.120|s
#
# The size in bytes is reported as separate `gauge` metric:
#
#   droplets-size:348|g
#
# Metric types are defined per https://github.com/etsy/statsd/blob/master/docs/metric_types.md
#

if [ $# -ne 1 ]; then
  echo "Error: Missing Argument."
  echo "Usage: statsd_pipe METRICS_LOG_FILE"
  exit 1
fi

#
# Grab the resource type from a request given as $1, e.g.
#
# PUT /droplets/7100a3b3-1eeb-49b1-ad52-747a1071a854/ HTTP/1.1
#
resource_type() {
  local uri_regexp='^([A-Z]+) \/([a-z_]+)\/'
  [[ "$1" =~ ${uri_regexp} ]];

  echo "${BASH_REMATCH[1]}-${BASH_REMATCH[2]}"
}

tail -n0 --retry -F $1 2>/dev/null | while read in; do
  IFS=\; read -a fields <<<"$in"

  request="${fields[0]}"
  resource_type=$(resource_type "$request")
  # multiply by 1000 to get ms, the only format possible with statsd timings
  time=$(echo ${fields[1]} 1000 | awk '{printf "%.0f\n",$1*$2}')
  bytes_sent="${fields[2]}"

  # note that nc behaves differently when actually feeding it with a file compared to piping directly from echo
  # feeding with a file makes -w0 actually work, whereas with piping using echo, it doesn't.'
  echo "$resource_type-time:$time|ms" > /tmp/bits-service-metric
  nc -u -w0 127.0.0.1 8125 < /tmp/bits-service-metric
  echo "$resource_type-time:$time|ms" > /tmp/bits-service-metric
  nc -u -w0 127.0.0.1 8125 < /tmp/bits-service-metric
done