#!/var/vcap/packages/ruby-2.3/bin/ruby
# frozen_string_literal: true

# A diagnostic endpoint for Statsd

require 'socket'

socket = UDPSocket.new
socket.bind('127.0.0.1', 8125)

loop do
  mesg, addr = socket.recvfrom(10_000)
  puts mesg
end
